# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wangpeng/WorkSpaceForMe/PlatformForMe/MyCloud/rpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wangpeng/WorkSpaceForMe/PlatformForMe/MyCloud/rpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangpeng/WorkSpaceForMe/PlatformForMe/MyCloud/rpc/CMakeFiles /home/wangpeng/WorkSpaceForMe/PlatformForMe/MyCloud/rpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangpeng/WorkSpaceForMe/PlatformForMe/MyCloud/rpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpc_server

# Build rule for target.
rpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc_server
.PHONY : rpc_server

# fast build rule for target.
rpc_server/fast:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/build
.PHONY : rpc_server/fast

rpc/Channel.o: rpc/Channel.cpp.o

.PHONY : rpc/Channel.o

# target to build an object file
rpc/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Channel.cpp.o
.PHONY : rpc/Channel.cpp.o

rpc/Channel.i: rpc/Channel.cpp.i

.PHONY : rpc/Channel.i

# target to preprocess a source file
rpc/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Channel.cpp.i
.PHONY : rpc/Channel.cpp.i

rpc/Channel.s: rpc/Channel.cpp.s

.PHONY : rpc/Channel.s

# target to generate assembly for a file
rpc/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Channel.cpp.s
.PHONY : rpc/Channel.cpp.s

rpc/DynamicThreadPool.o: rpc/DynamicThreadPool.cpp.o

.PHONY : rpc/DynamicThreadPool.o

# target to build an object file
rpc/DynamicThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/DynamicThreadPool.cpp.o
.PHONY : rpc/DynamicThreadPool.cpp.o

rpc/DynamicThreadPool.i: rpc/DynamicThreadPool.cpp.i

.PHONY : rpc/DynamicThreadPool.i

# target to preprocess a source file
rpc/DynamicThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/DynamicThreadPool.cpp.i
.PHONY : rpc/DynamicThreadPool.cpp.i

rpc/DynamicThreadPool.s: rpc/DynamicThreadPool.cpp.s

.PHONY : rpc/DynamicThreadPool.s

# target to generate assembly for a file
rpc/DynamicThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/DynamicThreadPool.cpp.s
.PHONY : rpc/DynamicThreadPool.cpp.s

rpc/MemoryPool.o: rpc/MemoryPool.cpp.o

.PHONY : rpc/MemoryPool.o

# target to build an object file
rpc/MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/MemoryPool.cpp.o
.PHONY : rpc/MemoryPool.cpp.o

rpc/MemoryPool.i: rpc/MemoryPool.cpp.i

.PHONY : rpc/MemoryPool.i

# target to preprocess a source file
rpc/MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/MemoryPool.cpp.i
.PHONY : rpc/MemoryPool.cpp.i

rpc/MemoryPool.s: rpc/MemoryPool.cpp.s

.PHONY : rpc/MemoryPool.s

# target to generate assembly for a file
rpc/MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/MemoryPool.cpp.s
.PHONY : rpc/MemoryPool.cpp.s

rpc/Policy.o: rpc/Policy.cpp.o

.PHONY : rpc/Policy.o

# target to build an object file
rpc/Policy.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Policy.cpp.o
.PHONY : rpc/Policy.cpp.o

rpc/Policy.i: rpc/Policy.cpp.i

.PHONY : rpc/Policy.i

# target to preprocess a source file
rpc/Policy.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Policy.cpp.i
.PHONY : rpc/Policy.cpp.i

rpc/Policy.s: rpc/Policy.cpp.s

.PHONY : rpc/Policy.s

# target to generate assembly for a file
rpc/Policy.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Policy.cpp.s
.PHONY : rpc/Policy.cpp.s

rpc/TaskQueue.o: rpc/TaskQueue.cpp.o

.PHONY : rpc/TaskQueue.o

# target to build an object file
rpc/TaskQueue.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TaskQueue.cpp.o
.PHONY : rpc/TaskQueue.cpp.o

rpc/TaskQueue.i: rpc/TaskQueue.cpp.i

.PHONY : rpc/TaskQueue.i

# target to preprocess a source file
rpc/TaskQueue.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TaskQueue.cpp.i
.PHONY : rpc/TaskQueue.cpp.i

rpc/TaskQueue.s: rpc/TaskQueue.cpp.s

.PHONY : rpc/TaskQueue.s

# target to generate assembly for a file
rpc/TaskQueue.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TaskQueue.cpp.s
.PHONY : rpc/TaskQueue.cpp.s

rpc/TcpServer.o: rpc/TcpServer.cpp.o

.PHONY : rpc/TcpServer.o

# target to build an object file
rpc/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TcpServer.cpp.o
.PHONY : rpc/TcpServer.cpp.o

rpc/TcpServer.i: rpc/TcpServer.cpp.i

.PHONY : rpc/TcpServer.i

# target to preprocess a source file
rpc/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TcpServer.cpp.i
.PHONY : rpc/TcpServer.cpp.i

rpc/TcpServer.s: rpc/TcpServer.cpp.s

.PHONY : rpc/TcpServer.s

# target to generate assembly for a file
rpc/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/TcpServer.cpp.s
.PHONY : rpc/TcpServer.cpp.s

rpc/Util.o: rpc/Util.cpp.o

.PHONY : rpc/Util.o

# target to build an object file
rpc/Util.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Util.cpp.o
.PHONY : rpc/Util.cpp.o

rpc/Util.i: rpc/Util.cpp.i

.PHONY : rpc/Util.i

# target to preprocess a source file
rpc/Util.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Util.cpp.i
.PHONY : rpc/Util.cpp.i

rpc/Util.s: rpc/Util.cpp.s

.PHONY : rpc/Util.s

# target to generate assembly for a file
rpc/Util.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/Util.cpp.s
.PHONY : rpc/Util.cpp.s

rpc/test_memory_pool.o: rpc/test_memory_pool.cpp.o

.PHONY : rpc/test_memory_pool.o

# target to build an object file
rpc/test_memory_pool.cpp.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/test_memory_pool.cpp.o
.PHONY : rpc/test_memory_pool.cpp.o

rpc/test_memory_pool.i: rpc/test_memory_pool.cpp.i

.PHONY : rpc/test_memory_pool.i

# target to preprocess a source file
rpc/test_memory_pool.cpp.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/test_memory_pool.cpp.i
.PHONY : rpc/test_memory_pool.cpp.i

rpc/test_memory_pool.s: rpc/test_memory_pool.cpp.s

.PHONY : rpc/test_memory_pool.s

# target to generate assembly for a file
rpc/test_memory_pool.cpp.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc/test_memory_pool.cpp.s
.PHONY : rpc/test_memory_pool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rpc_server"
	@echo "... rpc/Channel.o"
	@echo "... rpc/Channel.i"
	@echo "... rpc/Channel.s"
	@echo "... rpc/DynamicThreadPool.o"
	@echo "... rpc/DynamicThreadPool.i"
	@echo "... rpc/DynamicThreadPool.s"
	@echo "... rpc/MemoryPool.o"
	@echo "... rpc/MemoryPool.i"
	@echo "... rpc/MemoryPool.s"
	@echo "... rpc/Policy.o"
	@echo "... rpc/Policy.i"
	@echo "... rpc/Policy.s"
	@echo "... rpc/TaskQueue.o"
	@echo "... rpc/TaskQueue.i"
	@echo "... rpc/TaskQueue.s"
	@echo "... rpc/TcpServer.o"
	@echo "... rpc/TcpServer.i"
	@echo "... rpc/TcpServer.s"
	@echo "... rpc/Util.o"
	@echo "... rpc/Util.i"
	@echo "... rpc/Util.s"
	@echo "... rpc/test_memory_pool.o"
	@echo "... rpc/test_memory_pool.i"
	@echo "... rpc/test_memory_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

